services:
  db:
    tty: true
    stdin_open: true
    image: postgres:alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: company-sales-db-dev # Default to development DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - company-sales-network
    ports:
      - 5432:5432
  web:
    tty: true
    stdin_open: true
    build:
      context: .
      args:
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
    volumes:
      - .:/app
      - bundle_path:/usr/local/bundle
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME} # Use environment variable for DB name
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - company-sales-network

volumes:
  postgres_data:
  bundle_path:
networks:
  company-sales-network:
