services:
  db:
    tty: true
    stdin_open: true
    image: postgres:alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: company-sales-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - company-sales-network
    ports:
      - 5432:5432
  web:
    tty: true
    stdin_open: true
    build: .
    volumes:
      - .:/app
      - bundle_path:/usr/local/bundle
    environment:
      DB_HOST: db
      DB_NAME: company-sales-db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      RAILS_MASTER_KEY: f0869c37b822b72deb675caee0ec9c9e
    ports:
      - "3000:80"
    depends_on:
      - db
    networks:
      - company-sales-network

volumes:
  postgres_data:
  bundle_path:
networks:
  company-sales-network:
